// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StrongTypeResource
{
    using System.Reflection;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    internal partial class WrapperGenerator : Transformation
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("//-----------------------------------------------------------------------------\r\n" +
                    "//\r\n//\tThis code was generated by a ");
            
            #line 5 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Assembly.GetExecutingAssembly().GetName().Name));
            
            #line default
            #line hidden
            this.Write(" Version ");
            
            #line 5 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Assembly.GetExecutingAssembly().GetName().Version.ToString()));
            
            #line default
            #line hidden
            this.Write(".\r\n//\r\n//\tChanges to this file may cause incorrect behavior and will be lost if\r\n" +
                    "//\tthe code is regenerated.\r\n//\r\n//---------------------------------------------" +
                    "--------------------------------\r\n\r\nnamespace ");
            
            #line 12 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.NameSpace));
            
            #line default
            #line hidden
            this.Write(" {\r\n\tusing System;\r\n\tusing System.Diagnostics;\r\n\tusing System.Diagnostics.CodeAna" +
                    "lysis;\r\n\tusing System.Globalization;\r\n\tusing System.Runtime.CompilerServices;\r\n\t" +
                    "using System.ComponentModel;\r\n\tusing System.Resources;\r\n");
            
            #line 20 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
if(this.Pseudo) {
            
            #line default
            #line hidden
            this.Write("\tusing System.Collections.Generic;\r\n\tusing System.Reflection;\r\n");
            
            #line 23 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
}
            
            #line default
            #line hidden
            
            #line 24 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
if(this.FlowDirection) {
            
            #line default
            #line hidden
            this.Write("\tusing System.Windows;\r\n");
            
            #line 26 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
}
            
            #line default
            #line hidden
            this.Write(@"
	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated.
	// To add or remove a member, edit your .ResX file then rerun MsBuild,
	// or rebuild your VS project.
	[DebuggerNonUserCode]
	[CompilerGenerated]
	");
            
            #line 36 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
if(this.IsPublic) {
            
            #line default
            #line hidden
            this.Write("\t[SuppressMessage(\"Maintainability\", \"CA1515:Consider making public types interna" +
                    "l\")]\r\n\t");
            
            #line 38 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
}
            
            #line default
            #line hidden
            this.Write("\t[SuppressMessage(\"Naming\", \"CA1724:Type names should not match namespaces\")]\r\n\t");
            
            #line 40 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.IsPublic ? "public" : "internal"));
            
            #line default
            #line hidden
            this.Write(" static class ");
            
            #line 40 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClassName));
            
            #line default
            #line hidden
            this.Write(@" {

		/// <summary>
		/// Overrides the current thread's CurrentUICulture property for all
		/// resource lookups using this strongly typed resource class.
		/// </summary>
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public static CultureInfo");
            
            #line 47 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.AllowNull));
            
            #line default
            #line hidden
            this.Write(" Culture { get; set; }\r\n\r\n\t\t/// <summary>\r\n\t\t/// Used for formating of the resour" +
                    "ce strings. Usually same as CultureInfo.CurrentCulture.\r\n\t\t/// </summary>\r\n\t\t[Ed" +
                    "itorBrowsable(EditorBrowsableState.Advanced)]\r\n\t\tpublic static CultureInfo");
            
            #line 53 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.AllowNull));
            
            #line default
            #line hidden
            this.Write(" FormatCulture { get; set; }\r\n\r\n");
            
            #line 55 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
if(this.FlowDirection) {
            
            #line default
            #line hidden
            
            #line 56 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
	if(this.Pseudo) {
            
            #line default
            #line hidden
            this.Write("\t\tprivate static bool isRightToLeft = ((Environment.TickCount / 500) & 1) == 0;\r\n" +
                    "");
            
            #line 58 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
	}
            
            #line default
            #line hidden
            this.Write("\t\t/// <summary>\r\n\t\t/// Gets FlowDirection for current culture.\r\n\t\t/// </summary>\r" +
                    "\n\t\tpublic static FlowDirection FlowDirection {\r\n\t\t\tget {\r\n");
            
            #line 64 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
	if(!this.Pseudo) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\tbool isRightToLeft;\r\n\t\t\t\tif(");
            
            #line 66 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClassName));
            
            #line default
            #line hidden
            this.Write(".Culture != null && ");
            
            #line 66 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClassName));
            
            #line default
            #line hidden
            this.Write(".Culture.TextInfo != null) {\r\n\t\t\t\t\tisRightToLeft = ");
            
            #line 67 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClassName));
            
            #line default
            #line hidden
            this.Write(@".Culture.TextInfo.IsRightToLeft;
				} else if(CultureInfo.CurrentUICulture != null && CultureInfo.CurrentUICulture.TextInfo != null) {
					isRightToLeft = CultureInfo.CurrentUICulture.TextInfo.IsRightToLeft;
				} else if(CultureInfo.CurrentCulture != null && CultureInfo.CurrentCulture.TextInfo != null) {
					isRightToLeft = CultureInfo.CurrentCulture.TextInfo.IsRightToLeft;
				} else {
					isRightToLeft = false;
				}
");
            
            #line 75 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
	}
            
            #line default
            #line hidden
            this.Write("\t\t\t\treturn isRightToLeft ? FlowDirection.RightToLeft : FlowDirection.LeftToRight;" +
                    "\r\n\t\t\t}\r\n\t\t}\r\n");
            
            #line 79 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\tprivate static ");
            
            #line 81 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pseudo ? "Pseudo" : ""));
            
            #line default
            #line hidden
            this.Write("ResourceManager");
            
            #line 81 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.AllowNull));
            
            #line default
            #line hidden
            this.Write(@" resourceManager;

		/// <summary>
		/// Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public static ResourceManager ResourceManager {
			get {
				if(resourceManager == null) {
					resourceManager = new ");
            
            #line 90 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pseudo ? "Pseudo" : ""));
            
            #line default
            #line hidden
            this.Write("ResourceManager(\"");
            
            #line 90 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceName));
            
            #line default
            #line hidden
            this.Write("\", typeof(");
            
            #line 90 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClassName));
            
            #line default
            #line hidden
            this.Write(").Assembly);\r\n\t\t\t\t}\r\n\t\t\t\treturn resourceManager;\r\n\t\t\t}\r\n\t\t}\r\n");
            
            #line 95 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
if(this.Pseudo) {
            
            #line default
            #line hidden
            this.Write(@"
		/// <summary>
		/// Performs pseudo localization of string resources
		/// </summary>
		private sealed class PseudoResourceManager : ResourceManager {
			private static Dictionary<char, char> map = new Dictionary<char, char> {
				{ 'a', 'ä' },
				{ 'b', '\u0183' },
				{ 'c', 'č' },
				{ 'd', 'ƌ' },
				{ 'e', 'ë' },
				{ 'f', 'ƒ' },
				{ 'g', 'ğ' },
				{ 'h', 'ħ' },
				{ 'i', 'ï' },
				{ 'j', 'ĵ' },
				{ 'k', 'ƙ' },
				{ 'l', 'ł' },
				{ 'm', 'ɱ' },
				{ 'n', 'ň' },
				{ 'o', 'ö' },
				{ 'p', 'þ' },
				{ 'q', 'ɋ' },
				{ 'r', 'ř' },
				{ 's', 'š' },
				{ 't', 'ŧ' },
				{ 'u', 'ü' },
				{ 'v', 'ṽ' },
				{ 'w', 'ŵ' },
				{ 'x', 'ӿ' },
				{ 'y', 'ŷ' },
				{ 'z', 'ž' },
				{ 'A', 'Ä' },
				{ 'B', '\u0181' },
				{ 'C', 'Č' },
				{ 'D', 'Đ' },
				{ 'E', 'Ë' },
				{ 'F', 'Ƒ' },
				{ 'G', 'Ğ' },
				{ 'H', 'Ħ' },
				{ 'I', 'Ï' },
				{ 'J', 'Ĵ' },
				{ 'K', 'Ҟ' },
				{ 'L', 'Ł' },
				{ 'M', 'Ӎ' },
				{ 'N', 'Ň' },
				{ 'O', 'Ö' },
				{ 'P', 'Ҏ' },
				{ 'Q', 'Ǫ' },
				{ 'R', 'Ř' },
				{ 'S', 'Š' },
				{ 'T', 'Ŧ' },
				{ 'U', 'Ü' },
				{ 'V', 'Ṽ' },
				{ 'W', 'Ŵ' },
				{ 'X', 'Ӿ' },
				{ 'Y', 'Ŷ' },
				{ 'Z', 'Ž' },
			};

			private Dictionary<string, string> resources = new Dictionary<string, string>();

			public PseudoResourceManager(string baseName, Assembly assembly) : base(baseName, assembly) {
			}

			public override string");
            
            #line 161 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.AllowNull));
            
            #line default
            #line hidden
            this.Write(" GetString(string name, CultureInfo");
            
            #line 161 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.AllowNull));
            
            #line default
            #line hidden
            this.Write(" culture) {\r\n\t\t\t\tif(culture == null) {\r\n\t\t\t\t\treturn this.Pseudo(name);\r\n\t\t\t\t}\r\n\t\t" +
                    "\t\treturn base.GetString(name, culture);\r\n\t\t\t}\r\n\r\n\t\t\tpublic string");
            
            #line 168 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.AllowNull));
            
            #line default
            #line hidden
            this.Write(" GetBaseString(string name, CultureInfo");
            
            #line 168 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.AllowNull));
            
            #line default
            #line hidden
            this.Write(" culture) {\r\n\t\t\t\treturn base.GetString(name, culture);\r\n\t\t\t}\r\n\r\n\t\t\t[SuppressMessa" +
                    "ge(\"Security\", \"CA5394:Do not use insecure randomness\")]\r\n\t\t\tpublic string");
            
            #line 173 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.AllowNull));
            
            #line default
            #line hidden
            this.Write(" GetBaseString(string[] values, string name, CultureInfo");
            
            #line 173 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.AllowNull));
            
            #line default
            #line hidden
            this.Write(" culture) {\r\n\t\t\t\tstring");
            
            #line 174 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.AllowNull));
            
            #line default
            #line hidden
            this.Write(@" text;
				if(!this.resources.TryGetValue(name, out text)) {
					Random random = new Random();
					this.resources[name] = text = values[random.Next(values.Length)];
					Debug.WriteLine(""Pseudo Localizing {0} to value {1}"", name, text);
				}
				return text;
			}

			private string");
            
            #line 183 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.AllowNull));
            
            #line default
            #line hidden
            this.Write(" Pseudo(string name) {\r\n\t\t\t\tstring");
            
            #line 184 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.AllowNull));
            
            #line default
            #line hidden
            this.Write(" text;\r\n\t\t\t\tif(!this.resources.TryGetValue(name, out text)) {\r\n\t\t\t\t\tthis.resource" +
                    "s[name] = text = PseudoResourceManager.PseudoLocalize(base.GetString(name, null)" +
                    ");\r\n\t\t\t\t}\r\n\t\t\t\treturn text;\r\n\t\t\t}\r\n\r\n\t\t\tprivate static string PseudoLocalize(str" +
                    "ing");
            
            #line 191 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.AllowNull));
            
            #line default
            #line hidden
            this.Write(@" text) {
				if(text == null) {
					text = string.Empty;
				}
				char[] result = new char[text.Length];
				bool open = false; // open means loop index i is inside of the format item. So no translations should happen as all the character are format specifiers.
				for(int i = 0; i < text.Length; i++) {
					char c = text[i];
					if(!open && c == '{') {
						if(i + 1 < text.Length && text[i + 1] == '{') {
							result[i++] = c;
						} else {
							open = i + 1 < text.Length && '0' <= text[i + 1] && text[i + 1] <= '9';
						}
					} else if(open && c == '}') {
						if(i + 1 < text.Length && text[i + 1] == '}') {
							result[i++] = c;
						} else {
							open = false;
						}
					}
					char pseudo;
					if(!open && map.TryGetValue(c, out pseudo)) {
						c = pseudo;
					}
					result[i] = c;
				}
				return ""[-~="" + new string(result) + ""=~-]"";
			}
		}
");
            
            #line 221 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
}
            
            #line default
            #line hidden
            
            #line 222 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
foreach(ResourceItem item in this.Items) {
            
            #line default
            #line hidden
            this.Write("\r\n\t\t/// <summary>\r\n\t\t/// Looks up a localized string similar to ");
            
            #line 225 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Comment()));
            
            #line default
            #line hidden
            this.Write(".\r\n\t\t/// </summary>\r\n");
            
            #line 227 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
	if(item.Parameters != null) {
            
            #line default
            #line hidden
            this.Write(" \t\tpublic static string ");
            
            #line 228 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 228 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ParametersDeclaration()));
            
            #line default
            #line hidden
            this.Write(") {\r\n\t\t\treturn string.Format(FormatCulture, ");
            
            #line 229 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.GetStringExpression(this.Pseudo)));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 229 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\", Culture)");
            
            #line 229 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.NotNull));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 229 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ParametersInvocation()));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t}\r\n");
            
            #line 231 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
	} else if(item.Type == "string") {
            
            #line default
            #line hidden
            this.Write(" \t\tpublic static string ");
            
            #line 232 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" {\r\n\t\t\tget { return ");
            
            #line 233 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.GetStringExpression(this.Pseudo)));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 233 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\", Culture)");
            
            #line 233 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.NotNull));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t}\r\n");
            
            #line 235 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
	} else {
            
            #line default
            #line hidden
            this.Write(" \t\tpublic static ");
            
            #line 236 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 236 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" {\r\n\t\t\tget { return (");
            
            #line 237 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type));
            
            #line default
            #line hidden
            this.Write(")ResourceManager.GetObject(\"");
            
            #line 237 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\", Culture)");
            
            #line 237 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.NotNull));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t}\r\n");
            
            #line 239 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
	}
            
            #line default
            #line hidden
            
            #line 240 "C:\Projects\StrongTypeResource\StrongTypeResource\WrapperGenerator.tt"
}
            
            #line default
            #line hidden
            this.Write("\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
